package com.example.swifty_component.models

data class User(
    val achievements: List<Any>,
    val anonymize_date: String,
    val campus: List<Campu>,
    val campus_users: List<CampusUser>,
    val correction_point: Int,
    val cursus_users: List<CursusUser>,
    val displayname: String,
    val email: String,
    val expertises_users: List<ExpertisesUser>,
    val first_name: String,
    val groups: List<Any>,
    val id: Int,
    val image_url: String,
    val languages_users: List<LanguagesUser>,
    val last_name: String,
    val location: Any,
    val login: String,
    val partnerships: List<Any>,
    val patroned: List<Patroned>,
    val patroning: List<Any>,
    val phone: Any,
    val pool_month: String,
    val pool_year: String,
    val projects_users: List<Project>,
    val staff : Boolean,
    val titles: List<Any>,
    val titles_users: List<Any>,
    val url: String,
    val usual_first_name: String,
    val usual_full_name: String,
    val wallet: Int
)